C     NAMING CONVENTIONS USED -
C      A-G       REAL IN COMMON BLOCK
C      H         CHARACTER IN COMMON BLOCK
C      HZ        CHARACTER, INTERNAL
C      I-J       INTEGER, INTERNAL
C      KP        PARAMETER IN COMMON BLOCK
C      K         PARAMETER, INTERNAL
C      L         LOGICAL IN COMMON BLOCK
C      LZ        LOGICAL, INTERNAL
C      M         INTEGER, INTERNAL
C      N         INTEGER IN COMMON BLOCK
C      O-Y       REAL IN COMMON BLOCK
C      Z         INTERNAL      
      


      PROGRAM SOLVE
      PARAMETER (ISZ=10, ILINES=10)
      INTEGER IANS
      INTEGER, DIMENSION(ILINES, ISZ) :: IAR, ISEEN
      CHARACTER(ISZ) HINPUT
      IANS=0

C     INPUT READING IS TRICKY DUE TO NO DELIMITER
      OPEN(1, FILE='input.txt', STATUS='old')

      READ(1,*)  HINPUT
      READ(HINPUT(J:J),*) IEL




      PRINT*,"ANSWER IS: ", IANS
      END PROGRAM

