################################################################################
#              Makefile for the ADVENT OF CODE                                 #
################################################################################

prun:
	python3 psol.py input.txt
prun1: 
	python3 psol1.py input.txt
prun2:
	python3 psol2.py input.txt

ptest:
	python3 psol.py test.txt
ptest1: 
	python3 psol1.py test.txt
ptest2: 
	python3 psol2.py test.txt


